### ISSUE TITLE
websocket SSL failure on chrome

### ISSUE THREAD

**Issue by dckc** [RevDefine/revdefine#24]
I see in the console:

```
app.cc725c59.js:1 WebSocket connection to 'ws://observer-us.services.mainnet.rchain.coop:40403/ws/events' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR
```

See also:
https://stackoverflow.com/questions/50704614/websocket-connection-fails-on-chrome-without-ssl
https://bugs.chromium.org/p/chromium/issues/detail?id=378566

**Comment by zsluedem** [comment]
I supposed that you are using Chrome.

I don't really know how to deal with that. It looks like Chrome force using https(wss). It doesn't happen in firefox and safari.

Coop is going to make all the observer server use https(ws). I hope that would solve the problem.

**Comment by zsluedem** [comment]
https://github.com/RevDefine/revdefine/pull/30
coop support https now. It should be fine now. Feel free to reopen if you have other questions.

**Comment by dckc** [comment]
revdefine.io still tries to use http... Or do i have a cache problem?

**Comment by zsluedem** [comment]
> revdefine.io still tries to use http... Or do i have a cache problem?

What I mean is the observer servers of the coop.
Nvm, I will update revdefine.io to https recently.
